### ISSUE TITLE
KeyError: 'COLON' in local block

### ISSUE THREAD

**Issue by tbugfinder** [amplify-education/python-hcl2#27]
Hello,

using tf 0.12.24 I'm deploying an ECS environment specifying the ECS task configuration inline within `main.tf`:
```
locals {
  name = "blueprint-ecs-fargate-test-default"

  tags = {
    Name       = "${local.name}-${local.id}"
    Deployment = "test fixture default"
  }

  container_definitions = [
    {
      cpu         = var.fargate_cpu,
      image       = var.app_image,
      memory      = var.fargate_memory,
      name        = "app",
      networkMode = "awsvpc",
      portMappings = [
        {
          containerPort = var.app_port,
          hostPort      = var.app_port
        }
      ],
      "environment": [
        {
          "Name" : "SOME_BASE64",
          "Value" :  base64encode(file("input.conf"))
        }
      ],
      "entryPoint": [
        "sh",
        "-c",
        "set -ueo pipefail;  /usr/sbin/syslog-ng -F"
      ]
    }
  ]
}

```
Using given main.tf `python-hcl2` stops although terraform 0.12.24 applies the configuration successfully.

```
/main.tf
       Traceback (most recent call last):
         File "/newproject/.venv/lib/python3.7/site-packages/lark/parsers/lalr_parser.py", line 62, in get_action
           return states[state][token.type]
       KeyError: 'COLON'

       During handling of the above exception, another exception occurred:

       Traceback (most recent call last):
         File "./.venv/bin/hcl2tojson", line 28, in <module>
           json.dump(hcl2.parse(in_file.read()), out_file)
         File "/newproject/.venv/lib/python3.7/site-packages/lark/lark.py", line 311, in parse
           return self.parser.parse(text, start=start)
         File "/newproject/.venv/lib/python3.7/site-packages/lark/parser_frontends.py", line 89, in parse
           return self._parse(token_stream, start, *[sps] if sps is not NotImplemented else [])
         File "/newproject/.venv/lib/python3.7/site-packages/lark/parser_frontends.py", line 54, in _parse
           return self.parser.parse(input, start, *args)
         File "/newproject/.venv/lib/python3.7/site-packages/lark/parsers/lalr_parser.py", line 36, in parse
           return self.parser.parse(*args)
         File "/newproject/.venv/lib/python3.7/site-packages/lark/parsers/lalr_parser.py", line 86, in parse
           action, arg = get_action(token)
         File "/newproject/.venv/lib/python3.7/site-packages/lark/parsers/lalr_parser.py", line 65, in get_action
           raise UnexpectedToken(token, expected, state=state)
       lark.exceptions.UnexpectedToken: Unexpected token Token(COLON, ':') at line 22, column 20.
       Expected one of:
        * LSQB
        * TRUE
        * __ANON_6
        * LBRACE
        * __ANON_9
        * __ANON_3
        * __ANON_10
        * PLUS
        * __ANON_11
        * DECIMAL
        * __ANON_5
        * SLASH
        * QMARK
        * PERCENT
        * MORETHAN
        * LPAR
        * BANG
        * LESSTHAN
        * __ANON_7
        * __ANON_4
        * MINUS
        * FALSE
        * STRING_LIT
        * NULL
        * STAR
        * __ANON_8
        * EQUAL

```
Within AWS console the json configuration is given:
```
{
  "ipcMode": null,
  "executionRoleArn": null,
  "containerDefinitions": [
    {
      "dnsSearchDomains": null,
      "logConfiguration": null,
      "entryPoint": [
        "sh",
        "-c",
        "set -ueo pipefail;  /usr/sbin/syslog-ng -F"
      ],
      "portMappings": [
        {
          "hostPort": 514,
          "protocol": "tcp",
          "containerPort": 514
        }
      ],
      "command": null,
      "linuxParameters": null,
      "cpu": 512,
      "environment": [
        {
          "name": "SOME_BASE64",
          "value": "ddddddddddddddddddddddddddddddddddddddddddddddddddddd="
        }
      ],
      "resourceRequirements": null,
      "ulimits": null,
      "dnsServers": null,
      "mountPoints": [],
      "workingDirectory": null,
      "secrets": null,
      "dockerSecurityOptions": null,
      "memory": 1024,
      "memoryReservation": null,
      "volumesFrom": [],
      "stopTimeout": null,
      "image": "balabit/syslog-ng:latest",
      "startTimeout": null,
      "firelensConfiguration": null,
      "dependsOn": null,
      "disableNetworking": null,
      "interactive": null,
      "healthCheck": null,
      "essential": true,
      "links": null,
      "hostname": null,
      "extraHosts": null,
      "pseudoTerminal": null,
      "user": null,
      "readonlyRootFilesystem": null,
      "dockerLabels": null,
      "systemControls": null,
      "privileged": null,
      "name": "app"
    }
  ],
  "placementConstraints": [],
  "memory": "1024",
  "taskRoleArn": null,
  "compatibilities": [
    "EC2",
    "FARGATE"
  ],
  "taskDefinitionArn": "arn:aws:ecs:eu-west-1:333333333333333:task-definition/app-dddddddd:1",
  "family": "app-7777777",
  "requiresAttributes": [
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.docker-remote-api.1.18"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "ecs.capability.task-eni"
    }
  ],
  "pidMode": null,
  "requiresCompatibilities": [
    "FARGATE"
  ],
  "networkMode": "awsvpc",
  "cpu": "512",
  "revision": 1,
  "status": "ACTIVE",
  "inferenceAccelerators": null,
  "proxyConfiguration": null,
  "volumes": []
}
```

Although I was able to use '=' instead of ':' within local.container_definitions it looks like there's a difference between python-hcl2 and terraform hcl2 validator.

Thanks & Best

**Comment by acdha** [comment]
I had been under the impression that the use of colons in maps had been deprecated but it definitely doesn't trigger a deprecation warning now and

**Comment by aoskotsky-amplify** [comment]
Didn't realize the spec allows colons now. Created this PR to add it to the parser https://github.com/amplify-education/python-hcl2/pull/46. Let me know there are any issues with the fix. I'll have it merged soon
